'use strict';

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up(queryInterface, Sequelize) {
    /**
     * Add seed commands here.
     *
     * Example:
     * await queryInterface.bulkInsert('People', [{
     *   name: 'John Doe',
     *   isBetaMember: false
     * }], {});
     */
    await queryInterface.bulkInsert(
      'Breeds',

      [
        // ---------------------- DOGS (1–25) ----------------------
        {
          id: 1,
          name: 'German Shepherd',
          species: 'Dog',
          description: 'A smart, loyal, and highly trainable working dog.',
          image: 'german_shepherd.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 2,
          name: 'Golden Retriever',
          species: 'Dog',
          description: 'Friendly, intelligent, and great with families.',
          image: 'golden_retriever.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 3,
          name: 'Labrador Retriever',
          species: 'Dog',
          description: 'Outgoing, even-tempered, and highly versatile.',
          image: 'labrador_retriever.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 4,
          name: 'Bulldog',
          species: 'Dog',
          description: 'Calm, courageous, and easygoing with a distinctive appearance.',
          image: 'bulldog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 5,
          name: 'Poodle',
          species: 'Dog',
          description: 'Highly intelligent, active, and known for hypoallergenic fur.',
          image: 'poodle.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 6,
          name: 'Beagle',
          species: 'Dog',
          description: 'Curious, friendly, and excellent scent hound.',
          image: 'beagle.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 7,
          name: 'Rottweiler',
          species: 'Dog',
          description: 'Strong, confident, and protective working dog.',
          image: 'rottweiler.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 8,
          name: 'Siberian Husky',
          species: 'Dog',
          description: 'Energetic, friendly, and famous for blue eyes.',
          image: 'siberian_husky.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 9,
          name: 'Doberman Pinscher',
          species: 'Dog',
          description: 'Alert, fearless, and loyal guard dog.',
          image: 'doberman_pinscher.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 10,
          name: 'Shih Tzu',
          species: 'Dog',
          description: 'Affectionate toy breed with a luxurious coat.',
          image: 'shih_tzu.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 11,
          name: 'Great Dane',
          species: 'Dog',
          description: 'Gentle giants known for size and gentle temperament.',
          image: 'great_dane.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 12,
          name: 'Chihuahua',
          species: 'Dog',
          description: 'Smallest dog breed with a big personality.',
          image: 'chihuahua.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 13,
          name: 'Boxer',
          species: 'Dog',
          description: 'Energetic, playful, and loyal family guardians.',
          image: 'boxer.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 14,
          name: 'Dachshund',
          species: 'Dog',
          description: 'Lively and brave, famous for their long bodies.',
          image: 'dachshund.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 15,
          name: 'Border Collie',
          species: 'Dog',
          description: 'Extremely intelligent and energetic herding dog.',
          image: 'border_collie.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 16,
          name: 'Australian Shepherd',
          species: 'Dog',
          description: 'Smart, work-driven herders with striking eyes.',
          image: 'australian_shepherd.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 17,
          name: 'Corgi',
          species: 'Dog',
          description: 'Small herding dogs with big ears and bigger personality.',
          image: 'corgi.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 18,
          name: 'Pug',
          species: 'Dog',
          description: 'Charming, mischievous with a wrinkly face.',
          image: 'pug.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 19,
          name: 'Mastiff',
          species: 'Dog',
          description: 'Massive, powerful, yet gentle protectors.',
          image: 'mastiff.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 20,
          name: 'Akita',
          species: 'Dog',
          description: 'Loyal and dignified dogs originating from Japan.',
          image: 'akita.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 21,
          name: 'Shiba Inu',
          species: 'Dog',
          description: 'Alert, agile, fox-like Japanese breed.',
          image: 'shiba_inu.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 22,
          name: 'French Bulldog',
          species: 'Dog',
          description: 'Playful, adaptable, and perfect for apartments.',
          image: 'french_bulldog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 23,
          name: 'Yorkshire Terrier',
          species: 'Dog',
          description: 'Tiny but brave with a silky coat.',
          image: 'yorkshire_terrier.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 24,
          name: 'Bernese Mountain Dog',
          species: 'Dog',
          description: 'Large, gentle dogs known for tri-color coats.',
          image: 'bernese_mountain_dog.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 25,
          name: 'Cocker Spaniel',
          species: 'Dog',
          description: 'Sweet, affectionate, and great family dogs.',
          image: 'cocker_spaniel.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },

        // ---------------------- CATS (26–50) ----------------------
        {
          id: 26,
          name: 'Persian Cat',
          species: 'Cat',
          description: 'Quiet, gentle with long fluffy fur.',
          image: 'persian_cat.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 27,
          name: 'Maine Coon',
          species: 'Cat',
          description: 'Large, sociable cats known as gentle giants.',
          image: 'maine_coon.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 28,
          name: 'Siamese Cat',
          species: 'Cat',
          description: 'Vocal, affectionate, and sleek with blue eyes.',
          image: 'siamese_cat.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 29,
          name: 'Bengal Cat',
          species: 'Cat',
          description: 'Energetic cats with leopard-like markings.',
          image: 'bengal_cat.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 30,
          name: 'Ragdoll',
          species: 'Cat',
          description: 'Calm, fluffy cats that go limp when held.',
          image: 'ragdoll_cat.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 31,
          name: 'British Shorthair',
          species: 'Cat',
          description: 'Calm, chunky cats with dense coats.',
          image: 'british_shorthair.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 32,
          name: 'Sphynx',
          species: 'Cat',
          description: 'Hairless, affectionate, and attention-loving.',
          image: 'sphynx.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 33,
          name: 'Scottish Fold',
          species: 'Cat',
          description: 'Cute folded ears and sweet personality.',
          image: 'scottish_fold.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 34,
          name: 'Abyssinian',
          species: 'Cat',
          description: 'Active, playful, and one of the oldest breeds.',
          image: 'abyssinian.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 35,
          name: 'Birman',
          species: 'Cat',
          description: 'Blue-eyed, long-haired cats with white paws.',
          image: 'birman.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 36,
          name: 'Savannah',
          species: 'Cat',
          description: 'Tall, exotic cats with wild ancestry.',
          image: 'savannah.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 37,
          name: 'Russian Blue',
          species: 'Cat',
          description: 'Calm, elegant cats with silver-blue fur.',
          image: 'russian_blue.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 38,
          name: 'Norwegian Forest Cat',
          species: 'Cat',
          description: 'Large, sturdy cats built for cold climates.',
          image: 'norwegian_forest_cat.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 39,
          name: 'American Shorthair',
          species: 'Cat',
          description: 'Friendly, adaptable, and long-lived breed.',
          image: 'american_shorthair.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 40,
          name: 'Himalayan',
          species: 'Cat',
          description: 'Persian-like cats with colorpoint fur.',
          image: 'himalayan.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 41,
          name: 'Tonkinese',
          species: 'Cat',
          description: 'Social, vocal cats with striking eyes.',
          image: 'tonkinese.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 42,
          name: 'Oriental',
          species: 'Cat',
          description: 'Elegant cats with big ears and slim bodies.',
          image: 'oriental.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 43,
          name: 'Cornish Rex',
          species: 'Cat',
          description: 'Curly-coated cats with playful nature.',
          image: 'cornish_rex.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 44,
          name: 'Devon Rex',
          species: 'Cat',
          description: 'Elfin appearance and soft, wavy coat.',
          image: 'devon_rex.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 45,
          name: 'Turkish Van',
          species: 'Cat',
          description: 'Known as swimming cats with unique markings.',
          image: 'turkish_van.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 46,
          name: 'Japanese Bobtail',
          species: 'Cat',
          description: 'Short tail and playful, social personality.',
          image: 'japanese_bobtail.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 47,
          name: 'Manx',
          species: 'Cat',
          description: 'Tail-less breed known for strong hind legs.',
          image: 'manx.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 48,
          name: 'Chartreux',
          species: 'Cat',
          description: 'Quiet, muscular, blue-gray cats from France.',
          image: 'chartreux.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 49,
          name: 'Nebelung',
          species: 'Cat',
          description: 'Long-haired Russian Blue with silky fur.',
          image: 'nebelung.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: 50,
          name: 'Egyptian Mau',
          species: 'Cat',
          description: 'Spotted, elegant cats known for speed.',
          image: 'egyptian_mau.jpg',
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {}
    );
  },

  async down(queryInterface, Sequelize) {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     * await queryInterface.bulkDelete('People', null, {});
     */
    await queryInterface.bulkDelete('Breeds', null, {});
  },
};
